---
title: "income"
author: "Dang Minh Nhut - 22125071"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(car)
library(faraway)
library(corrplot)
library(dplyr)
library(GGally)
```

## Load data

```{r}
set.seed(452)
```

```{r}
df <- read.csv("income.csv")
head(df)
```

```{r}
dim(df)
```

```{r}
df$X <- NULL
```

### Factorize

```{r}
df$language <- as.factor(df$language)
df$sex <- as.factor(df$sex)
```

### NA

```{r}
sum(is.na(df))
```

```{r}
df <- na.omit(df)
sum(is.na(df))
```

### Duplications

```{r}
sum(duplicated(df))
```

### Plots

```{r}
par(mfrow = c(1, 3))
for (col in names(df)) {
  if (is.numeric(df[[col]]))
    hist(df[[col]], main = col, xlab = col, breaks = 30)
}
par(mfrow = c(1, 1))
```

```{r}
par(mfrow = c(1, 3))

for (col in names(df)) {
  if (is.numeric(df[[col]]))
    boxplot(df[col], main = col)
}

par(mfrow = c(1, 1))
```

```{r}
par(mfrow = c(1, 2))
hist(log(df$wages), main = 'wages', xlab = 'wages', breaks = 30)
boxplot(log(df$wages), main = 'wages')
par(mfrow = c(1, 1))
```

```{r}
ggpairs(df)
```

## Split

```{r}
# Define the split ratio
train_ratio <- 0.8

# Determine the number of rows in the training set
train_size <- floor(train_ratio * nrow(df))

# Randomly sample row indices for the training set
train_indices <- sample(seq_len(nrow(df)), size = train_size)

# Split the data into training and testing sets
train_set <- df[train_indices, ]
test_set <- df[-train_indices, ]

# Display the number of rows in each set
dim(train_set) # Should be approximately 80
dim(test_set)  # Should be approximately 20
```

## Model

```{r}
model_full <- lm(wages ~ ., data = df)
summary(model_full)
```

```{r}
model_quadratic <- lm(wages ~ poly(education, age, degree = 2) + sex + language, data = df)
summary(model_quadratic)
```

```{r}
model_cubic <- lm(wages ~ poly(education, age, degree = 3) + sex + language, data = df)
summary(model_cubic)
```

```{r}
model_log_cubic <- lm(log(wages) ~ poly(education, age, degree = 3) + sex, data = df)
summary(model_log_cubic)
```

```{r}
predictions <- exp(predict(model_log_quadratic, newdata = test_set))
# Actual values from the test set 
actual_values <- test_set$wages
# Calculate Mean Squared Error (MSE) 
mse <- mean((predictions - actual_values)^2)  
# Calculate R-squared 
rss <- sum((predictions - actual_values)^2) 
tss <- sum((actual_values - mean(actual_values))^2) 
r_squared <- 1 - (rss / tss)  
# Print metrics 
cat("Mean Squared Error (MSE):", mse, "\n") 
cat("R-squared:", r_squared, "\n")
```

```{r}
qqnorm(model_log_quadratic$residuals)
qqline(model_log_quadratic$residuals, col = "red")
```

```{r}
shapiro.test(model_log_quadratic$residuals)
```
