---
title: "redwine"
author: "Dang Minh Nhut - 22125071"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(car)
library(faraway)
library(corrplot)
library(dplyr)
library(GGally)
```

## Load data

```{r}
set.seed(452)
```

```{r}
df <- read.csv("redwine.csv")
head(df)
```

```{r}
dim(df)
```

```{r}
df$X <- NULL
```

### Factorize

```{r}
df$language <- as.factor(df$language)
df$sex <- as.factor(df$sex)
```

### NA

```{r}
sum(is.na(df))
```

```{r}
df <- na.omit(df)
sum(is.na(df))
```

### Duplications

```{r}
sum(duplicated(df))
```

### Plots

```{r}
par(mfrow = c(1, 3))
for (col in names(df)) {
  if (is.numeric(df[[col]]))
    hist(df[[col]], main = col, xlab = col, breaks = 30)
}
par(mfrow = c(1, 1))
```

```{r}
par(mfrow = c(1, 3))

for (col in names(df)) {
  if (is.numeric(df[[col]]))
    boxplot(df[col], main = col)
}

par(mfrow = c(1, 1))
```

```{r}
par(mfrow = c(1, 2))
hist(log(df$wages), main = 'wages', xlab = 'wages', breaks = 30)
boxplot(log(df$wages), main = 'wages')
par(mfrow = c(1, 1))
```

```{r}
ggpairs(df)
```

## Split

```{r}
# Define the split ratio
train_ratio <- 0.8

# Determine the number of rows in the training set
train_size <- floor(train_ratio * nrow(df))

# Randomly sample row indices for the training set
train_indices <- sample(seq_len(nrow(df)), size = train_size)

# Split the data into training and testing sets
train_set <- df[train_indices, ]
test_set <- df[-train_indices, ]

# Display the number of rows in each set
dim(train_set) # Should be approximately 80
dim(test_set)  # Should be approximately 20
```

## Model

```{r}
model_full <- lm(wages ~ ., data = df)
summary(model_full)
```
