---
title: "STAT452 Final Project"
author: "Luu Quoc Bao - 22125008, Le Minh Hoang - 22125029, Le Duc Nhuan - 22125070,
  Dang Minh Nhut - 22125071"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library

```{r}
library(ggplot2)
library(readxl)
library(car)
library(faraway)
library(corrplot)
library(dplyr)
```

## Activity 1

```{r}
set.seed(123)
```

### 1.1 Load and clean data

```{r}
df <- read.csv("auto_mpg.csv", header = TRUE, sep=";")
head(df)
```

```{r}
dim(df)
```

```{r}
nrow(df[df$horsepower == '?',])
is.numeric(df$horsepower)
```

```{r}
df = df[df$horsepower != '?',]
dim(df)

df$horsepower <- as.numeric(df$horsepower)
is.numeric(df$horsepower)
```

```{r}
sum(duplicated(df))
```

```{r}
summary(df)
```

#### Remove car names

```{r}
df$car_name <- NULL
dim(df)
```

#### Histograms

```{r}
par(mfrow = c(2, 4))
for (col in names(df)) {
  if (is.numeric(df[[col]]))
    hist(df[[col]], main = paste("Histogram of", col), xlab = col, breaks = 30)
}
par(mfrow = c(1, 1))
```

#### Log Histogram

```{r}
par(mfrow = c(2, 4))
for (col in names(df)) {
  if (is.numeric(df[[col]]))
    hist(log(df[[col]]), main = paste("Histogram of", col), xlab = col, breaks = 30)
}
par(mfrow = c(1, 1))
```

```{r}
origin_counts <- table(df$origin)

barplot(origin_counts, main = "Origin Distribution", xlab = "Origin", ylab = "Count", col = c("blue", "pink", "green", "yellow"))
```

```{r}
cylinders_counts <- table(df$cylinders)

barplot(cylinders_counts, main = "Cylinders Distribution", xlab = "Cylinders", ylab = "Count", col = c("blue", "pink", "green", "yellow"))
```

```{r}
df$origin_id <- as.factor(df$origin)
df$origin_id
```

#### Boxplots & remove outliers

```{r}
par(mfrow = c(2, 4))

for (col in names(df)) {
  if (is.numeric(df[[col]]))
    boxplot(df[col], main = col)
}

par(mfrow = c(1, 1))
```

```{r}
# Function to remove outliers using IQR for a single column
identify_outliers_IQR <- function(x) {
  Q1 <- quantile(x, 0.25)
  Q3 <- quantile(x, 0.75)
  IQR <- Q3 - Q1
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  !(x >= lower_bound & x <= upper_bound)
}

# Identify outliers for each numeric column
outlier_matrix <- df %>%
  select(where(is.numeric)) %>%
  mutate(across(everything(), identify_outliers_IQR))

# Filter out rows with any outlier
df_clean <- df[!apply(outlier_matrix, 1, any), ]

dim(df_clean)
```

```{r}
# par(mfrow = c(2, 4))
# for (col in names(df_clean)) {
#   if (is.numeric(df_clean[[col]]))
#     hist(df_clean[[col]], main = paste("Histogram of", col), xlab = col, breaks = 30)
# }
# par(mfrow = c(1, 1))
```

```{r}
par(mfrow = c(2, 4))

for (col in names(df_clean)) {
  if (is.numeric(df_clean[[col]]))
    boxplot(df_clean[col], main = col)
}

par(mfrow = c(1, 1))
```

### 1.2 Split data

```{r}
df$log_weight <- log(df$weight)
df$log_displacement <- log(df$displacement)
df$log_horsepower <- log(df$horsepower)
df$sqr_weight <- (df$weight)^2
df$sqr_displacement <- (df$displacement)^2
df$sqr_horsepower <- (df$horsepower)^2
df$sqr_year <- (df$model_year)^2
# df$cylinder_id <- as.factor(df$cylinders)
# df$year_id <- as.factor(df$model_year)
```

```{r}
# Define the split ratio
train_ratio <- 0.8

# Determine the number of rows in the training set
train_size <- floor(train_ratio * nrow(df))

# Randomly sample row indices for the training set
train_indices <- sample(seq_len(nrow(df)), size = train_size)

# Split the data into training and testing sets
train_set <- df[train_indices, ]
test_set <- df[-train_indices, ]

# Display the number of rows in each set
dim(train_set) # Should be approximately 80
dim(test_set)  # Should be approximately 20
```

### 1.3 Model

#### Collinearity

```{r}
pairs(subset(df, select = - c(origin_id)))
```

```{r}
corrplot(cor(subset(df_clean, select = -origin_id)), method = "number")
```

```{r}
par(mfrow = c(2, 4))

for (col in names(train_set)) {
  if (is.numeric(train_set[[col]]))
    boxplot(train_set[col], main = col)
}

par(mfrow = c(1, 1))
```

```{r}
# Function to remove outliers using IQR for a single column
identify_outliers_IQR <- function(x) {
  Q1 <- quantile(x, 0.25)
  Q3 <- quantile(x, 0.75)
  IQR <- Q3 - Q1
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  !(x >= lower_bound & x <= upper_bound)
}

# Identify outliers for each numeric column
outlier_matrix <- train_set %>%
  select(where(is.numeric)) %>%
  mutate(across(everything(), identify_outliers_IQR))

# Filter out rows with any outlier
train_set_cleaned <- train_set[!apply(outlier_matrix, 1, any), ]

dim(train_set_cleaned)
```

```{r}
par(mfrow = c(2, 5))

for (col in names(train_set_cleaned)) {
  if (is.numeric(train_set_cleaned[[col]]))
    boxplot(train_set_cleaned[col], main = col)
}

par(mfrow = c(1, 1))
```

```{r}
model_full <- lm(mgp ~ . - origin, data = train_set)
summary(model_full)
```

```{r}
car::vif(model_full)
```

```{r}
model_bw <- step(model_full, data = train_set, direction = "backward")
```

```{r}
summary(model_bw)
```

```{r}
model <- update(model_bw, . ~ .)
summary(model)
```

#### Evaluate the model

```{r}
predictions <- predict(model, newdata = test_set) 
# Actual values from the test set 
actual_values <- test_set$mgp
# Calculate Mean Squared Error (MSE) 
mse <- mean((predictions - actual_values)^2)  
# Calculate R-squared 
rss <- sum((predictions - actual_values)^2) 
tss <- sum((actual_values - mean(actual_values))^2) 
r_squared <- 1 - (rss / tss)  
# Print metrics cat("Mean Squared Error (MSE):", mse, "\n") 
cat("R-squared:", r_squared, "\n")
```

#### Validating residuals

```{r}
e <- predictions - actual_values
hist(e, main = "Histogram of Residuals", xlab = "Residuals", breaks = 50)
```

```{r}
qqnorm(e)
qqline(e, col = "red")
```

```{r}
shapiro.test(e)
```

## Activity 2
