---
title: "superstore"
author: "Dang Minh Nhut - 22125071"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(car)
library(faraway)
library(corrplot)
library(dplyr)
library(GGally)
```

## Load data

```{r}
set.seed(123)
```

```{r}
df <- read.csv("superstore.csv")
head(df)
```

```{r}
dim(df)
```

### NA

```{r}
sum(is.na(df))
```

```{r}
df <- na.omit(df)
sum(is.na(df))
```

### Duplications

```{r}
sum(duplicated(df))
```

### Format

```{r}
cat("Num postal codes:", length(unique(df$Postal.Code)), "\n")
cat("No. cities:", length(unique(df$City)), "\n")
cat("No. states:", length(unique(df$State)), "\n")
cat("No. countries:", length(unique(df$Country)), "\n")
cat("No. regions:", length(unique(df$Region)), "\n")
cat("No. products:", length(unique(df$Product.ID)), "\n")
cat("No. cats:", length(unique(df$Category)), "\n")
```

```{r}
df$Row.ID <- NULL
df$Order.ID <- NULL
df$Order.Date <- NULL
df$Ship.Date <- NULL
df$Customer.ID <- NULL
df$Customer.Name <- NULL
df$Country <- NULL # 1 country
df$City <- NULL
df$Postal.Code <- NULL # too much 
df$State <- NULL # used state
df$Product.ID <- NULL # too much 
df$Product.Name <- NULL
```

```{r}
df$Ship.Mode <- as.factor(df$Ship.Mode)
df$Segment <- as.factor(df$Segment) 
df$Sub.Category <- as.factor(df$Sub.Category)
df$Region <- as.factor(df$Region)
```

```{r}
dim(df)
```

### Plots

```{r}
par(mfrow = c(2, 2))
for (col in names(df)) {
  if (is.numeric(df[[col]]))
    hist(df[[col]], main = col, xlab = col, breaks = 50)
}
par(mfrow = c(1, 1))
```

```{r}
par(mfrow = c(1, 4))

for (col in names(df)) {
  if (is.numeric(df[[col]]))
    boxplot(df[col], main = col)
}

par(mfrow = c(1, 1))
```

```{r}
ggpairs(subset(df, select = c(Ship.Mode, Segment, Region, Category, Profit)))
```

## Split

```{r}
# Define the split ratio
train_ratio <- 0.8

# Determine the number of rows in the training set
train_size <- floor(train_ratio * nrow(df))

# Randomly sample row indices for the training set
train_indices <- sample(seq_len(nrow(df)), size = train_size)

# Split the data into training and testing sets
train_set <- df[train_indices, ]
test_set <- df[-train_indices, ]

# Display the number of rows in each set
dim(train_set) # Should be approximately 80
dim(test_set)  # Should be approximately 20
```

## Model

```{r}
model_full <- lm(Profit ~ . , data = train_set)
summary(model_full)
```

```{r}
model_aic <- step(model_full, direction="backward")
summary(model_aic)
```

```{r}
model <- update(model_aic, .~. -Sales-Quantity-Discount + poly(Sales, Quantity, Discount, degree = 3))
summary(model)
```

```{r}
predictions <- predict(model, newdata = test_set)
# Actual values from the test set 
actual_values <- test_set$Profit
# Calculate Mean Squared Error (MSE) 
mse <- mean((predictions - actual_values)^2)  
# Calculate R-squared 
rss <- sum((predictions - actual_values)^2) 
tss <- sum((actual_values - mean(actual_values))^2) 
r_squared <- 1 - (rss / tss)  
# Print metrics 
cat("Mean Squared Error (MSE):", mse, "\n") 
cat("R-squared:", r_squared, "\n")
```

```{r}
qqnorm(model$residuals)
qqline(model$residuals, col = "red")
```

```{r}
shapiro.test(sample(model$residuals, 5000))
```

```{r}
hist(model$residuals, main = "Histogram of Residuals", xlab = "Residuals", breaks = 200)
```
